### ISSUE TITLE
CloudFormation을 통한 EC2 인스턴스 배포

### ISSUE THREAD

**Issue by choboss00** [choboss00/aws-networking-cloudnet-inflearn#5]
## AWS CloudFormation 서비스란?

AWS 클라우드 인프라를 코드 기반으로 정의하고 선언하는 방법입니다. ( IaC, Infrastructure as Code )

템플릿 파일을 활용하여 CloudFormation 위로 올린 뒤, 전달받은 파일을 바탕으로 스택을 생성합니다.
- 템플릿 파일 : json, yaml 코드 언어로 정의
- 스택 : aws 클라우드 인프라를 순차적으로 실행, 삭제 ( 도커와 비슷한 느낌? )

![image](https://github.com/choboss00/aws-networking-cloudnet-inflearn/assets/111727212/f348c729-4986-4d62-b3fc-7d42d1f56a81)

**Comment by choboss00** [comment]
탬플릿을 배포하여 CloudFormation 스택을 생성하면, 코드 정의에 따라 순차적으로 자동 생성됩니다.

![image](https://github.com/choboss00/aws-networking-cloudnet-inflearn/assets/111727212/5dd7ae67-38d5-4214-bbd0-db587328c1ff)

```yaml
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  LatestAmiId:
    Description: (DO NOT CHANGE)
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    AllowedValues:
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
```

키페어의 경우, 각자 사용하는 키페어가 다르니 입력해주면 됩니다.

AMI 는 최신 코드를 입력받도록 하였습니다.

Resource 를 통해, 자원설정을 해줄 수 있습니다.

```yaml
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: WebServer
      SecurityGroups:
        - !Ref MySG
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum install httpd -y
            systemctl start httpd && systemctl enable httpd
            echo "<h1>Test Web Server</h1>" > /var/www/html/index.html

  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
```

UserDate 를 통해, 자동으로 코드를 실행하도록 작성해줄 수도 있습니다.

MySG 에서 보안그룹을 적용할 수 있습니다.
